name: Deploy Portfolio to GitHub Pages

# Run this workflow on every push to the 'main' branch
on:
  push:
    branches: [ main ] # Change this to 'master' if that's your default branch

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use a version that matches your environment

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Build your Vite site
      - name: Build
        run: npm run build

      # 5. Deploy the built site to the 'gh-pages' branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This is the folder Vite builds to (usually 'dist')
          publish_dir: ./dist
          # This is the magic line that adds your custom domain
          cname: derickmokua.co.ke
